---
title: "anusplin"
output: github_document
---

<!-- ---
title: "anusplin"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{anusplin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
--- -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
library(spInterp)
library(data.table)
# library(ggplot2)
# library(Ipaper)
```

```{r}
dat <- dat_RH[, .(lon, lat, alt, RH)]
X <- dat[, .(lon, lat, alt)] %>% as.matrix()
Y <- dat[, .(RH)] %>% as.matrix()

res <- 1
range <- c(70, 140, 15, 55)
r_dem <- get_chinadem(res = res) %>% round(1)
f_dem <- "output/dem.asc"

write_dem(r_dem, f_dem, digits = 1)
```

# 1. anusplin

## 1.1. fast example
```{r}
outdir <- "output"

anusplin_make_param(dat, "RH", range, res, file.alt = f_dem, cvt.coef = 1e3) -> param
anusplin_write_setting(param, outdir, is.run = TRUE, overwrite = TRUE)
anusplin_read_output(param$lapgrd, outdir) -> ans

ans
```

## 1.2. 另外一种等价的调用方法

```{r}
spInterp_anusplin(X, Y, range = range, res = res, file.alt = f_dem)
```

## 1.3. k-fold cross validation
```{r}
r = kford_ml(X, Y, FUN = spInterp_anusplin, 
  range = range, res = res, file.alt = f_dem, kfold = 5)
r
```

# 2. 不考虑高程时的结果

```{r}
spInterp_anusplin(X, Y, range, res, file.alt = f_dem)
```

## 2.1. k-fold cross validation
```{r}
X = dat[, .(lon, lat, alt)] %>% as.matrix()
Y = dat[, .(RH)] %>% as.matrix()

r = kford_ml(X, Y, FUN = spInterp_anusplin, 
  file.alt = NULL, range = range, kfold = 5)
r
```

# 3. 与adw进行对比
```{r}
r <- kford_ml(X[, c("lon", "lat")], Y,
  FUN = spInterp_adw,
  range = range, res = res, cdd = 450
)
r
```


```{r}
## mask china
# shp <- vect("data-raw/shp/bou1_4p.shp")
# ra = rast(ans) %>% mask(shp)
# plot(ra)
# plot(shp, add = TRUE, col = "transparent")

## 原数据
# p <- ggplot(dat, aes(lon, lat, color = RH)) +
#   geom_point() +
#   scale_color_gradientn(colours = rcolors::get_color("amwg256", 12))
# write_fig(p, "Rplot2.pdf", 10, 5)
```
