```{r}
library(Ipaper)
library(ggplot2)



f_alt = system.file("anusplin_demo/china_dem_025deg.txt", package = "spInterp")
range <- c(69.625, 140.375, 14.625, 55.375)
# range <- c(70, 140, 15, 55) # 高程数据的range有误
```

```{r}
outdir = "output"

anusplin_make_param(dat, "RH", range, file.alt = f_alt) -> param
anusplin_write_setting(param, outdir, is.run = TRUE, overwrite = TRUE)
anusplin_read_output(param$lapgrd, outdir) -> res

res
```

```{r}
X = dat[, 2:4] %>% as.matrix()
Y = dat[, 5] %>% as.matrix()

r = kford_ml(X, Y, FUN = spInterp_anusplin, 
  file.alt = f_alt, range = range, kfold = 5)
r
```

```{r}
# 移除掉高程
X = dat %>% select.matrix(lon, lat)
Y = dat[, 5] %>% as.matrix()

r_nodem = kford_ml(X, Y, FUN = spInterp_anusplin, range = range, kfold = 5)
r_nodem
```

## 1. 带高程

### 1.1. option1
```{r}
# dat <- fread("debug.csv")
X <- dat[, 2:4] %>% as.matrix()
Y <- dat[, 5] %>% as.matrix()

data = as.data.table(cbind(X, Y))
outdir <- "output"

anusplin_make_param(data, "RH", range, file.alt = f_alt) -> param
anusplin_write_setting(param, outdir, is.run = TRUE, overwrite = TRUE)
anusplin_read_output(param$lapgrd, outdir) -> res

res
```
### 1.2. option2
```{r}
spInterp_anusplin(X, Y, range = range, file.alt = f_alt)
```

## 2. 不带高程

### 1.1. option1
```{r}
# dat <- fread("debug.csv")
X <- dat[, .(lon, lat, alt)] %>% as.matrix()
Y <- dat[, .(RH)] %>% as.matrix()

dat = cbind(X, Y) %>% as.data.table()
outdir <- "output"

anusplin_make_param(dat, "RH", range, file.alt = NULL) -> param
anusplin_write_setting(param, outdir, is.run = TRUE, overwrite = TRUE)
anusplin_read_output(param$lapgrd, outdir) -> res
res
```

```{r}
# spInterp_anusplin(X, Y, range = range, file.alt = NULL)
r = kford_ml(X, Y, FUN = spInterp_anusplin, 
  file.alt = f_alt, range = range, kfold = 5)
r
```

```{r}
# spInterp_anusplin(X, Y, range = range, file.alt = NULL)
r = kford_ml(X, Y, FUN = spInterp_anusplin, 
  file.alt = NULL, range = range, kfold = 5)
r
```


# 与adw进行对比
```{r}
r <- kford_ml(X[, c("lon", "lat")], Y,
  FUN = spInterp_adw,
  range = range, res = 0.25, cdd = 450
)
r
```

## 3. 结论

可以看到结果基本是正确的

```{r}
library(terra)
r  = rast(res) #%>% plot()
shp = vect("data-raw/shp/bou1_4p.shp")
r2 = mask(r,shp)

write_fig({plot(r2)}, 'Rplot.pdf', 10, 5)
```

```{r}
p = ggplot(dat, aes(lon, lat, color = RH)) + 
  geom_point() + 
  scale_color_gradientn(colours = rcolors::get_color("amwg256", 12))
write_fig(p, 'Rplot2.pdf', 10, 5)
```
